---
- name: Selfhealing playbook
  hosts: All
  
 tasks:
  - name: read JSON of problem status
    url: "{{dtproblemURL}}"
    method: Get
    debug:
      msg: "There is problem with service"
    when:
      (result.totalOpenProblemsCount == "1")    

 - name: Starting easytravel
    service:
       name: easytravel
       state: started 
	  
