- name: selfhealing
  hosts: all
  
  tasks:
  - name: read JSON of problem status
    uri:
     url: "{{dtproblemURL}}"
     method: GET
     return_content: yes
     status_code: 200
     body_format: json     
    register: output
    
  - debug:
      msg: "{{output.json.result.totalOpenProblemsCount==0}}"
 
  - name: restart the troubled service!!
    shell: java -jar /home/hkbhandari/dynatrace-easytravel-linux-x86_64.jar
    host: 3.135.60.235
