- name: selfhealing
  hosts: all
  vars:
   commentuser: "hk"
   payload:
    ProblemID: "{{ProblemID}}"
   -debug:
      msg: "{{ProblemID}}"
  
  tasks:
  - name: read JSON of problem status
    uri:
     url: "{{dtproblemURL}}"
     method: GET
     return_content: yes
     status_code: 200
     body_format: json     
    register: output
    
  - debug:
      msg: "{{output.json.result.totalOpenProblemsCount==1}}"
 
  - name: restart the troubled service!!
    shell: sh /home/hkbhandari/easytravel-2.0.0-x64/weblauncher/weblauncher.sh &
    
  - name: push success comment to dynatrace
    uri:
      url: "{{dtcommentapiurl}}"
      method: POST
      body_format: json
      body: "{ \"comment\": \"Invoked remediation action successfully executed.\", \"user\": \"{{commentuser}}\",\"context\": \"Ansible Tower\" }"
      when: state == "OPEN"
