- name: selfhealing
  hosts: all
  
  tasks:
  - name: read JSON of problem status
    uri:
     url: "{{dtproblemURL}}"
     method: GET
     body_format: json
     debug:
      msg: "There is problem with service"
    when:
      (json.result.totalOpenProblemsCount == 1)    

  - name: Starting easytravel
    service:
       name: easytravel
       state: started
